{% set version = "0.4.0.0" %}
{% set sha256 = "1d9921e9b04a5b9892870fd3481f7b08e6fa083a1a3848ad262819de19eb5e02" %}

package:
  name: slycot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/slycot/slycot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - numpy
    # conda-forge::scikit-build>=0.10.0 includes MACOSX_DEPLOYMENT_TARGET
    # patches from https://github.com/scikit-build/scikit-build/pull/441
    - scikit-build >=0.10.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - scipy
  imports:
    - slycot
  commands:
    - pytest --pyargs slycot  # [not win]
    - pytest --pyargs slycot -k "not test_xerbla_override"  # [win]

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - repagh
