{% set name = "slycot" %}
{% set version = "0.3.3" %}
{% set sha256 = "d98ec859a398af8a3917a0d62e0724996c8b3e780813f8685410525aed9fbafd" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}  # [win]

  host:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas  # [not win]
    - m2w64-openblas  # [win]
    - numpy

  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas  # [not win]
    - m2w64-openblas  # [win]
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
