{% set version = "0.5.1.dev1" %}

package:
  name: slycot
  version: {{ version }}

source:
  # DO NOT MERGE THIS !
  git_url: https://github.com/bnavigator/Slycot.git
  git_rev: findpython

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.19,!=1.23.0                  # [build_platform != target_platform]
    - scikit-build >=0.15                    # [build_platform != target_platform]
    - setuptools >=45                        # [build_platform != target_platform]
    - setuptools_scm >=6.3                   # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - cmake >=3.14
    - make  # [linux]
    - flang >=11  # [win]
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - numpy >=1.19,!=1.23.0
    - scikit-build >=0.15
    - pip
    - setuptools >=45
    - setuptools_scm >=6.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win]

test:
  requires:
    - pytest
    - scipy
  imports:
    - slycot
  commands:
    - pytest --pyargs slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - roryyorke
    - bnavigator
    - moorepants
    - murrayrm
    - repagh
