{% set name = "slycot" %}
{% set version = "0.3.4.0" %}
{% set sha256 = "63e648b2be8c8ba0322a5fe286bdcf0e8d28a0c12e9ab1510f2a8725fc1283ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
    - flang                      # [win]

  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - openblas  # [not win]
    - mkl  # [win]
    - python
    - numpy
    - scikit-build

  run:
    - libflang                   # [win]
    - openblas
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - repagh
