appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DsDDhrCSOyjPt5OuTyMkllNGu5QvFlrzCd0W+aiycnfdTot5FqXa3Sj+sQKmOyay1dCJFqWPxV32JKzO0ki1+G4c1s4q52obICpk4cEzPCHHQH5tmPU5vCzYIfC8dKD3LkKDYa9mdxf4qQ7dUgi2yFTKGiI4PeWCh1POwQKVhp/ilsSWsC8kuPqSWVEYvYXlIUubd0yQCviDFWIgSBdKej9G4Jhs5a8c+jxoMRnbJEiKf+zBwWQm4+dRBoRzQsZlCyXD9JaHMXY/Rx+HM3cCcVooHc/gJRe2mZ93Tg20UQzV95Pz/NGXDvjSt8BwgPrRDzVmVd2weE79+gX9UVda3RXcElOPF4nWPGEBID29Yodi/1vWqT4Cp5DS30lIGOvUzChjbbJkPloRW1ITCvHilZzr4nvm3rPVDSVPIu1NwpMkhT4B3s6ytCwtQzpA4bJiiJBRxXlQrKBaj1VrU8KRPf40ysh1Y6ihZnbS8CHmxNXM2FT21LA+Gxc/1ypUhoYHgmSoJiUeLkx6siq24I2v+Q0C1j/7DswGsI7P+BC3m74rkVcHc0B5YQLmh/GL13tnScUrouiAwciUvCBT9NAxPiKZKQNk/yCag0qc6vlUj1vMPVDeUNqYpB7EqwA482aNXg5IHjWgF5L6kNfMpKLSoBdgf4YDuYRLhn4k9ZQKfKs=}
